<tr>
    <td>{{$entry->user->username}}</td>
    <td>{{$entry->category->title}}</td>
    <td>{{$entry->title}}</td>
    <td>{{$entry->content}}</td>
    <td>{{$entry->priority}}</td>
    <td>{{$entry->deadline}}</td>
    <td>{{$entry->tags}}</td>
</tr>
